SEVERE_ISSUES = {
    'EMPTY_TITLE',
    'EMPTY_CONTENT',
    'HTTP_ERROR',
    'ENCODING_ERROR',
    'INVALID_URL',
}

WARNING_ISSUES = {
    'SHORT_CONTENT',
    'DATE_PARSE_ERROR',
    'TRAILING_NOISE',
    'NAVIGATION_NOISE',
    'TAG_POLLUTION',
}
